name: BotshotIndicator
version: '${project.version}'
main: bowshot.highpurity.cc.botshotindicator.BotshotIndicator
api-version: 1.18
load: STARTUP
authors: [ Highpurity ]
description: Plugin that notifies the user whenever you hit an opponent with a bow shot!
website: https://highpurity.cc
